In [3]:
import os
import gym
import gym_donkeycar
import numpy as np

path = f"/home/o/Applications/DonkeySimLinux/"
app_path = f"{path}/donkey_sim.x86_64"

port = 9091

conf = {
    "exe_path": app_path,
    "port": port
}

env = gym.make("donkey-generated-roads-v0", conf=conf)

obs = env.reset()

for i in range(100):
    action = env.action_space.sample() #! does this work?
    obs, reward, done, info = env.step(action)
    print(obs, reward, done, info)

env.close()

starting DonkeyGym env
Setting default: start_delay 5.0
Setting default: max_cte 8.0
Setting default: frame_skip 1
Setting default: cam_resolution (120, 160, 3)
Setting default: log_level 20
Setting default: host localhost
Setting default: steer_limit 1.0
Setting default: throttle_min 0.0
Setting default: throttle_max 1.0
donkey subprocess started
Found path: /home/o/Applications/DonkeySimLinux//donkey_sim.x86_64


INFO:gym_donkeycar.core.client:connecting to localhost:9091 


loading scene generated_road


INFO:gym_donkeycar.envs.donkey_sim:on need car config
INFO:gym_donkeycar.envs.donkey_sim:sending car config.
INFO:gym_donkeycar.envs.donkey_sim:sim started!


[[[106 134 173]
  [106 134 173]
  [105 133 172]
  ...
  [103 129 166]
  [104 130 167]
  [104 130 167]]

 [[106 134 173]
  [106 134 173]
  [106 134 173]
  ...
  [104 130 167]
  [104 130 167]
  [104 130 167]]

 [[107 135 174]
  [107 135 174]
  [107 135 174]
  ...
  [105 131 168]
  [105 131 168]
  [105 131 168]]

 ...

 [[ 85  86  88]
  [ 86  87  89]
  [ 91  92  94]
  ...
  [227 229 226]
  [205 207 204]
  [162 164 161]]

 [[ 89  90  92]
  [ 88  89  91]
  [ 91  92  94]
  ...
  [213 218 212]
  [212 217 211]
  [211 216 210]]

 [[ 98  99 101]
  [ 94  95  97]
  [ 95  96  98]
  ...
  [210 215 209]
  [214 219 213]
  [223 228 222]]] 2.4214268090272224e-07 False {'pos': (6.25202989578247, 0.0716668218374252, 6.2450156211853), 'cte': 0.000210966711165383, 'speed': 4.1162570596498e-06, 'forward_vel': 2.4214906657674567e-07, 'hit': 'none', 'gyro': (1.57089971253299e-06, -1.8577143237053e-06, -0.00012847017205786), 'accel': (-5.10882746311836e-05, -4.03759950131644e-05, 8.42539429868339e-06), 'vel': (